In [3]:
# creating dataframe using list of list : 
import pandas as pd 
data = [["ishika", 98], ["gaurav", 97], ["mahak", 90], ["deepanshi", 94]] 
df = pd.DataFrame(data) 
print(df)

           0   1
0     ishika  98
1     gaurav  97
2      mahak  90
3  deepanshi  94

In [4]:
df = pd.DataFrame(data, columns = ["Name", "Marks"])
print(df)

        Name  Marks
0     ishika     98
1     gaurav     97
2      mahak     90
3  deepanshi     94

In [6]:
# creating dataframe using dictionary of list :
import pandas as pd 
data = {'A' : [4,5,6], 'B' : [10,12,16]}
df = pd.DataFrame(data) 
print(df)

   A   B
0  4  10
1  5  12
2  6  16

In [11]:
# creating dataframes using numpy arrays :
import numpy as np 
arr = np.array([[1,2], [3,4], [5,6], [7,8]])
df = pd.DataFrame(arr, columns = ["A", "B"])
print(df)

   A  B
0  1  2
1  3  4
2  5  6
3  7  8

In [3]:
# reading excel data : 
import pandas as pd
df = pd.read_excel("Data.xlsx")
df

        name school  marks
0     ishika   rmsg     91
1  deepanshi   rmsg     92
2     udbhav    dps     93
3     ayushi   rmsg     94
4       yash   rmsg     95
5     gaurav    ckc     96

In [8]:
# reading json data : 
df = pd.read_json("file.json") 
df

     name        lang
0  ishika      python
1  gaurav  javascript

In [11]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url) 
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 17.3 KB

In [15]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000