In [1]:
import pandas as pd
df = pd.read_csv("data3.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [2]:
# to know where the null value is present : true comes there 
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [3]:
# to know how many null values are present in a particular column :
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [8]:
# only those rows where no null values present : 
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [4]:
# removing those columns which contains missing values : 
df.dropna(axis = 1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [5]:
# filling missing values with 0 : 
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [6]:
# for filling the null values with their nearest forward values : 
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [7]:
# filling null values with their nearest backward values : 
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [8]:
# filling null values with the mean values : 
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [9]:
# loading duplicate data : 
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [10]:
# dropping dupliacted : 
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [11]:
df2 = df["Name"].str.lower()
df2

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: str

In [14]:
df["City"].str.contains("delhi", case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [16]:
# getting something in the form of list : 
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [19]:
df["City"].str.split("@")

0       [New York]
1          [Delhi]
2    [Los Angeles]
3          [Delhi]
4         [Mumbai]
5          [Delhi]
6       [New York]
7       [New York]
8          [Delhi]
Name: City, dtype: object

In [20]:
df2 = df.dropna().copy()
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [28]:
# use of .apply method :
df2["age group"] = df["Age"].apply(lambda x : "adult" if x > 25 else "young")
df2

    Name   Age         City Gender              Email   Join Date age group
0  Alice  25.0     New York      F  alice@example.com  01-05-2021     young
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     adult
4  David  22.0       Mumbai      M  david@example.com  12-11-2019     young
6  Alice  25.0     New York      F  alice@example.com  01-05-2021     young
7  Alice  25.0     New York      F  alice@example.com  01-05-2021     young

In [40]:
df2

    Name   Age         City Gender              Email   Join Date age group
0  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young
2    Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020     adult
4  David  22.0       Mumbai    NaN  david@example.com  12-11-2019     young
6  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young
7  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young

In [50]:
# Gender_map = {"M" : "Male", "F" : "Female"}
df2["Gender"] = df2["Gender"].map({"M" : "Male", "F" : "Female"})
df2

    Name   Age         City Gender              Email   Join Date age group
0  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young
2    Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020     adult
4  David  22.0       Mumbai    NaN  david@example.com  12-11-2019     young
6  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young
7  Alice  25.0     New York    NaN  alice@example.com  01-05-2021     young

In [47]:
# use of .replace() method :
df["City"].replace({"Delhi": "New Delhi", "Mumbai": "Bombay"})

0       New York
1      New Delhi
2    Los Angeles
3      New Delhi
4         Bombay
5      New Delhi
6       New York
7       New York
8      New Delhi
Name: City, dtype: str

In [49]:
df["Gender"].replace({"M" : "Male", "F" : "Female"})

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
Name: Gender, dtype: str