In [1]:
import pandas as pd
df = pd.read_csv("data2.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [14]:
# use of loc :
# df.loc[0:2, ["Actor", "Film", "IMDb"]]
# df["Actor"] 
df.loc[7, 'IMDb']

np.float64(6.5)

In [18]:
# use of iloc : 
# df.iloc[0:2, [0, 1]]
# df.iloc[7, 5]

np.float64(6.5)

In [19]:
# use of at : filter labelwise 
df.at[0, 'Actor']

'Shah Rukh Khan'

In [20]:
# use of iat : filter positionwise
df.iat[0,0]

'Shah Rukh Khan'

In [34]:
# df2 = df[(df["Genre"] == "Action")& (df["IMDb"] > 6)].copy()
# df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [24]:
# use of .query() :
df.query("IMDb > 6 and Genre == 'Comedy'")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [37]:
df2.loc[0, 'Actor'] == "gaurav yadav"
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2