In [2]:
import pandas as pd 
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees, departments, on = "DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
# left join : 
pd.merge(employees, departments, on = "DeptID", how = "left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [7]:
# right join :  
pd.merge(employees, departments, on = "DeptID", how = "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [20]:
# outer join : 
pd.merge(employees, departments, on = "DeptID", how = "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [11]:
# concatenating two df : 
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score" : [434, 630]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age" : [20,21]})

pd.concat([df1, df2])

      Name  Score   Age
0    Alice  434.0   NaN
1      Bob  630.0   NaN
0  Charlie    NaN  20.0
1    David    NaN  21.0

In [12]:
df1

    Name  Score
0  Alice    434
1    Bob    630

In [13]:
df2

      Name  Age
0  Charlie   20
1    David   21

In [14]:
pd.concat([df1, df2], axis = 1)

    Name  Score     Name  Age
0  Alice    434  Charlie   20
1    Bob    630    David   21